version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    env_file:
      - .env
  api:
    image: izimio/kdb-ui:taker-academy-ui-1.0.0
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - app