version: '3'

services:
  back:
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
  front:
    image: izimio/kdb-ui:taker-academy-ui-1.0.0
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back